# Generated by Django 5.2.12 on 2026-04-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingentry',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('restaurant', 'Restaurant'), ('snack', 'Snack'), ('other', 'Other')], default='groceries', max_length=20),
        ),
    ]
