from django.urls import path
from .views import (
    InventoryListView,
    InventoryAddView,
    InventoryUpdateView,
    InventoryDeleteView,
    ProductLookupView,
    ScanHistoryListView,
    ScanHistoryAddView,
    UserProductListCreateView,
    UserProductDetailView,
    UserProductVoteView,
    AdminProductReviewListView,
    AdminProductReviewActionView,
    AdminPendingCountView,
    QuickAddInventoryView,
    ProductSearchView,
)

urlpatterns = [
    path('', InventoryListView.as_view(), name='inventory-list'),
    path('add/', InventoryAddView.as_view(), name='inventory-add'),
    path('quick-add/', QuickAddInventoryView.as_view(), name='inventory-quick-add'),
    path('search/', ProductSearchView.as_view(), name='inventory-search'),
    path('<int:pk>/update/', InventoryUpdateView.as_view(), name='inventory-update'),
    path('<int:pk>/delete/', InventoryDeleteView.as_view(), name='inventory-delete'),
    path('product/<str:barcode>/', ProductLookupView.as_view(), name='product-lookup'),
    path('scans/', ScanHistoryListView.as_view(), name='scan-history-list'),
    path('scans/add/', ScanHistoryAddView.as_view(), name='scan-history-add'),
    path('user-products/', UserProductListCreateView.as_view(), name='user-product-list'),
    path('user-products/<int:pk>/', UserProductDetailView.as_view(), name='user-product-detail'),
    path('user-products/<int:pk>/vote/', UserProductVoteView.as_view(), name='user-product-vote'),
    path('admin/products/', AdminProductReviewListView.as_view(), name='admin-product-list'),
    path('admin/products/<int:pk>/review/', AdminProductReviewActionView.as_view(), name='admin-product-review'),
    path('admin/products/count/', AdminPendingCountView.as_view(), name='admin-product-count'),
]
