# Generated by Django 5.2.12 on 2026-04-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_healthsnapshot_medicaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthsnapshot',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
    ]
