# Generated by Django 5.2.12 on 2026-04-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_foodintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodintake',
            name='date',
            field=models.DateField(db_index=True, default='2026-01-01'),
        ),
        migrations.AddField(
            model_name='foodintake',
            name='source_type',
            field=models.CharField(choices=[('scan', 'Scan'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='foodintake',
            name='unit_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodintake',
            name='consumed_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
