# Generated by Django 5.2.12 on 2026-04-13 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventoryitem_image_url_and_more'),
        ('users', '0007_foodintake_date_foodintake_source_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodintake',
            name='confidence_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='foodintake',
            name='weekday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='foodintake',
            index=models.Index(fields=['user', 'date'], name='users_foodi_user_id_9dc501_idx'),
        ),
    ]
