# Generated by Django 5.2.12 on 2026-05-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_medical_subtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('eat_healthy', 'Eat Healthy')], default='eat_healthy', max_length=20),
        ),
    ]
