# Generated by Django 5.2.12 on 2026-03-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('grains', 'Grains'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.CharField(blank=True, choices=[('refrigerator', 'Refrigerator'), ('freezer', 'Freezer'), ('pantry', 'Pantry'), ('cabinet', 'Cabinet')], default='', max_length=20),
        ),
    ]
