# Generated by Django 5.2.12 on 2026-03-26 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_scanhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('family', 'Family')], default='personal', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('user', 'barcode', 'inventory_type')},
        ),
    ]
