# Generated by Django 5.2.12 on 2026-03-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='consumption_per_use',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='uses_per_week',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
