# Generated by Django 5.2.12 on 2026-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_consumption_per_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
